---
- name: Configure repo
  trix_repos:
    remote_repo: "{{ item.repo }}"
    remote_key:  "{{ item.key | default(None)}}"
    local_repo:  "{{ local_repo | default(default_local_repo) }}"
    local_key:   "{{ local_key | default(None) }}"
    name:        "{{ item.name | default(None) }}"
    use_local:   "{{ local_install | default(False) }}"
  with_items: "{{ repos }}"

# Disable all remote repost (without *-local suffix)
# If we have local install
#
- block:

  # FIXME
  # Was trying to do it via yum_repos, lineinfile or ini_file
  # modules. Got monstrous construction at the end.
  - name: Install yum-utils to make yum-config-manager available
    yum:
      name: yum-utils
      state: installed

  - name: Disable all repo without '*-local' suffix
    shell: >
      yum-config-manager  \
      | sed -n 's/^\[\(.*\)\]$/\1/p' \
      | egrep -v "\-local$" \
      | xargs yum-config-manager --disable {}

    args:
      warn: no

  when: local_install | default(False)
