---
- name: Fetch remote .repo definitions
  get_url:
    url: "{{ item.repo }}"
    dest: /etc/yum.repos.d
  with_items: "{{ repos }}"
  when: item.repo|match('^http[s]*://.*\\.repo$')

- name: Copy local .repo definitions
  copy:
    src: "{{ item.repo }}"
    dest: /etc/yum.repos.d
  with_items: "{{ repos }}"
  when:
    - item.repo|search('\\.repo$')
    - not item.repo|search('^http[s]*://')

- name: Install repo RPMs from repository
  yum:
    name: "{{ item.repo }}"
    state: installed
  with_items: "{{ repos }}"
  when:
    - not item.repo|search('\\.rpm$')
    - not item.repo|search('\\.repo$')
    - not item.repo|search('^http[s]*://')
    - not item.repo|search('^/')

- name: Install repo RPMs
  yum:
    name: "{{ item.repo }}"
    state: installed
  with_items: "{{ repos }}"
  when: item.repo|search('\\.rpm$')

- name: Import GPG keys
  rpm_key:
    key: "{{ item.key }}"
    state: present
  with_items: "{{ repos }}"
  when: item.key|default([])

- name: Define remote repos
  yum_repository:
    file: "{{ item.name if item.name|default([]) else
              item.repo|regex_replace('^http[s]*://([^/]*)/.*','\\1') }}"
    name: "{{ item.name if item.name|default([]) else
              item.repo|regex_replace('^http[s]*://','')|
              regex_replace('/$','')|replace('/','-') }}"
    description: "Remote repo at {{ item.repo }}"
    baseurl: "{{ item.repo }}"
    enabled: yes
    gpgcheck: "{{ 'yes' if item.key|default([]) else 'no' }}"
    gpgkey: "{{ item.key|default([]) }}"
    state: present
  with_items: "{{ repos }}"
  when:
    - item.repo|search('^http[s]*://')
    - not (item.repo|search('\\.rpm$') or item.repo|search('\\.repo$'))

# Disable all remote repost (without *-local suffix)
# If we have local install
#
- block:

  # FIXME
  # Was trying to do it via yum_repos, lineinfile or ini_file
  # modules. Got monstrous construction at the end.
  - name: Install yum-utils to make yum-config-manager available
    yum:
      name: yum-utils
      state: installed

  - name: Diable all repo without '*-local' suffix
    shell: >
      yum repolist -q \
      | awk '
        /-local[^/-]/{next}
        NR==1{next}
        {
          gsub("^!", "", $1);
          gsub("/.*", "", $1);
          print $1
        }' \
      | xargs yum-config-manager --disable {}
    args:
      warn: no

  when: local_install
